"""empty message

Revision ID: 1bcc002aa681
Revises: 618431dcb84d
Create Date: 2025-07-27 22:28:28.641228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcc002aa681'
down_revision: Union[str, Sequence[str], None] = '618431dcb84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_top_tracks', sa.Column('genius_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_top_tracks', 'genius_id')
    # ### end Alembic commands ###
